### ISSUE TITLE
How do i remove the favicon on tabs?

### ISSUE THREAD

**Issue by Prakash4844** [gurusabarish/hugo-profile#112]
I have Changed The favicon File everywhere but the icon on tab is still the Hugo Pink Logo. How can i Change it ? 

Here's the ![image](https://user-images.githubusercontent.com/81550376/226113481-d0543b9a-359c-4596-bbfb-f7a5667ebf60.png)

**Comment by Prakash4844** [comment]
it changed automatically now

**Comment by hrokr** [comment]
For others, the favicon can be found in your `hugo.toml` or `hugo.yaml` file under params.
