### ISSUE TITLE
Images in blog posts doesn't get scaled for mobile devices. 

### ISSUE THREAD

**Issue by Prakash4844** [gurusabarish/hugo-profile#113]
![Screenshot_2023-03-18-21-24-43-770_org.mozilla.fenix.jpg](https://user-images.githubusercontent.com/81550376/226116690-3298d601-1bab-4844-915f-21c98fc5054c.jpg)

![Screenshot_2023-03-18-21-24-35-421_org.mozilla.fenix.jpg](https://user-images.githubusercontent.com/81550376/226116692-e6737d68-645b-42e1-affe-02650a3912d2.jpg)

See the screenshots above the images are for desktop size but should be scaled for android devices.

I am using Firefox on android 12 on Poco x3 pro India.

**Comment by gurusabarish** [comment]
@Prakash4844 check now

**Comment by Prakash4844** [comment]
Thanks, now it's working as expected.

Thanks again for this amazing template.
