### ISSUE TITLE
Local static website does not render as expected. (Netlify deploy and local build&serve work well)

### ISSUE THREAD

**Issue by shamiek** [gurusabarish/hugo-profile#117]
**Describe the bug**
Deployment on netlify and using `hugo server` (building and serving the site locally) work as expected. However, locally generating the static website to a `public` directory does not work as expected. There is no styling, no responsive clicks. There is just a plain html webpage when I open `public/index.html`

**To Reproduce**
1. hugo new site my-site -f=yaml
2. `cd themes`
3. `git clone https://github.com/gurusabarish/hugo-profile.git`
4. `cd ..`
5. Copy `config.yaml` from [here](https://raw.githubusercontent.com/gurusabarish/hugo-profile/master/exampleSite/config.yaml) and create `my-site/config.yaml`
6. `hugo --destination public`
7. Open `my-site/public/index.html` in a browser (I tried firefox and chrome)

**Expected behavior**
You should see a website exactly as how `hugo server` serves at `localhost:1313`.

**Screenshots**
![sc1](https://user-images.githubusercontent.com/22326175/231307362-e07e3073-68f0-429f-9d5e-933f8e135840.png)
![sc2](https://user-images.githubusercontent.com/22326175/231307511-ccc86e66-f743-4299-a21b-874bb52b8072.png)
![sc3](https://user-images.githubusercontent.com/22326175/231307579-e37ef676-17ea-464b-966f-c9729203711a.png)
![sc4](https://user-images.githubusercontent.com/22326175/231307618-707d9e25-c40c-43ad-9f1d-ce59133c2aa6.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04 LTS
 - Browser: Firefox (111.0.1 (64-bit)), Chrome (Version 112.0.5615.49 (Official Build) (64-bit))

**Additional context**
Netifly deployment and local build and serve work perfectly fine.

**Comment by Prakash4844** [comment]
Hey i also had this problem while deploying with GitHub actions.

Try this line in config.yaml

canonifyURLs: true

Hope this helps.

**Comment by shamiek** [comment]
Thanks a lot. Adding `canonifyURLs: true ` worked.
