### ISSUE TITLE
How can i change the Blog card's Description text?

### ISSUE THREAD

**Issue by Prakash4844** [gurusabarish/hugo-profile#118]
How can i change the Blog card's Description text? it is just whatever is written inside my blog posts. Can we set it explicitly?
![image](https://user-images.githubusercontent.com/81550376/231424466-46e4acf8-1059-4bd6-87aa-1841ce706395.png)

I have tried adding description in blog post's front-matter but it doesn't change.

**Comment by aviralgoel** [comment]
This is native behavior with Hugo. 
Read more here: https://gohugo.io/content-management/summaries/#manual-summary-splitting

Solution:
in your blogpost.md
Begin the blog post with the box of text you wish to be the description.

```
"Hey this article is going to be about..."
<!--more-->
"Your actual article here which may include all sorts of formatting like heading etc."
```
