### ISSUE TITLE
Github Pages is Broken

### ISSUE THREAD

**Issue by smkplus** [gurusabarish/hugo-profile#122]
I tried multiple times and everything works in local but when I push on github pages everything is broken

![image](https://github.com/gohugoio/hugoBasicExample/assets/16706911/b917a764-9459-4cf7-bb47-f60c65b0ddbe)

here is my baseURL
baseURL: "https://smkplus.github.io/MyRepo.github.io"

**Comment by arnydo** [comment]
@smkplus I have the same issue. Did you figure this out? It looks like the CSS/JS paths aren't following the baseUrl...

**Comment by smkplus** [comment]
@arnydo no I used this 
https://github.com/hugo-fixit/FixIt
