### ISSUE TITLE
Change/Remove Social Media Links on Blog Posts

### ISSUE THREAD

**Issue by carsonslater** [gurusabarish/hugo-profile#146]
I have searched the all the directories and everything is nearly perfect on my new site, except that I cannot change the icons and links for the Social Media posts on the blog posts (see image).

<img width="1450" alt="Screenshot 2023-12-27 at 11 50 03 PM" src="https://github.com/gurusabarish/hugo-profile/assets/98668121/25f32881-b6b0-4ead-a984-c8599802c041">

I would love to at a bare minimum know which file contains the scripts to change these icons and links, and I would also know how to remove them. The defaults do not match my social accounts linked on my home page.

I've pretty much only found things titled 'WhatsApp", "Twitter," and "Envelope" in the fab icon folders, but none of them are scripts (well some are .js, but I don't think editing those would do me any good). My tactic has been to search in my finder app (I'm on a M1 Pro Mac), to find the title of the minipage there called "Social" but I have had no luck. 

I'd love some help here - Thanks.

**Comment by carsonslater** [comment]
I'm not sure I am understanding those right - are these buttons for the reader to easily be able to share on social media? Even still, if that is the case, I'd still like to know how to remove them or change the twitter logo to the X logo.

**Comment by carsonslater** [comment]
I found out that if you change `{{ if .Params.socialShare | default false }}` in `single.html` to false you can get rid of the social media sharing! Case closed.

**Comment by zavocc** [comment]
TIL you can just put this into your site params if you don't want to disable this globally for all sites
![image](https://github.com/gurusabarish/hugo-profile/assets/119603393/6271bde3-d758-4e03-9711-ae9af9158a35)

**Comment by carsonslater** [comment]
This is awesome - thanks!
