### ISSUE TITLE
How do I get started?

### ISSUE THREAD

**Issue by pragyanone** [gurusabarish/hugo-profile#149]
I am unable to find where to change the website content: add my name and other information.
Please guide me.
Thank you.

**Comment by bjtn1** [comment]
Hey! I'm also trying to figure this out. Have you made any progress on this?

**Comment by pragyanone** [comment]
Oh ya, you can change them in exampleSite/config.yaml

**Comment by pragyanone** [comment]
oh ya, you change them in exampleSite/config.yaml
