### ISSUE TITLE
Search results display Template page

### ISSUE THREAD

**Issue by Orlokun** [gurusabarish/hugo-profile#161]
When using the search bar, the results will lead to the example page instead of the expected results. 
Repro steps: 
1. Open web page
2. In search bar, search a term that shows at least one result
3. Click any of the results
4. <b> Notice you will be redirected to the example web site instead of the expected page</b>

Expected Behavior
When a result is clicked, the user should be redirected to the respective webpage.

**Screenshots**
![image](https://github.com/gurusabarish/hugo-profile/assets/28856061/c0f746b3-ed00-488d-8f1e-891593f06ca8)
![image](https://github.com/gurusabarish/hugo-profile/assets/28856061/5aae49fa-cc08-494a-a2a8-882b4449fcdc)

 - OS: Windows 11
 - Browser: Edge
 - Version: Version 122.0.2365.59 (Official build) (64-bit)

**Comment by gurusabarish** [comment]
Kindly check you site configurations

**Comment by Orlokun** [comment]
Hi @gurusabarish Thanks for the answer. Sorry not reply sooner. 
What configurations do you mean?  This is the hugo file. 
Thanks! 

![image](https://github.com/gurusabarish/hugo-profile/assets/28856061/4d1836b9-6b40-4d4b-a51a-b89a822de258)

**Comment by Orlokun** [comment]
Ok I fixed it on my end. My issue was that I was being sent to the template page when pressed the search results. 

My config was fine, the problem was that on the baseUrl parameter at the beginning of the hugo file, I hadn't applied my site URL. and still had the template as base Url
