### ISSUE TITLE
Links under "Things I do" section ?

### ISSUE THREAD

**Issue by dombraccia** [gurusabarish/hugo-profile#20]
Hey @gurusabarish,

Thanks for all the previous help with the site design. I really like this format.

I have a request for a feature to add to the site layout - would it be possible to add the ability to attach links to the sections of  the "Things I do" section on the home page? I really like the look of the boxes with image and text, but I currently cannot make them clickable. It would be great if someone viewing my site could quickly navigate to examples of my work from that section I think it would make for a more friction-less experience. 

Let me know if this seems reasonable or if there would be challenges to implementing it.

**Comment by gurusabarish** [comment]
Hii @dombraccia, Thanks for your words

It's already added, you can find the configuration details [here](https://github.com/gurusabarish/hugo-profile/blob/master/website/v2.yaml). 

Can you suggest some more features or ideas ?

thanks,

**Comment by gurusabarish** [comment]
@dombraccia, Hope! you find,

Thanks ❤️
Gurusabarish
