### ISSUE TITLE
How to run this template

### ISSUE THREAD

**Issue by josephjosedev** [gurusabarish/hugo-profile#21]
i am new comer in hugo ,i would like to know about the configuration of this template.i follow the steps described in your repo .after run **hugo serve** i get blank page ,please help me.

**Comment by gurusabarish** [comment]
Hi @josephjosedev, make you are using versions in congfig file. Here the steps,

## Hugo theme format
- Clone this repo inside your themes folder and create config.yaml ( I am not much aware about toml. So, I am using yaml format. ) inside root folder and use one of these [v1config](https://github.com/gurusabarish/hugo-profile/blob/master/website/v1.yaml), [v2config](https://github.com/gurusabarish/hugo-profile/blob/master/website/v2.yaml), [v3config](https://github.com/gurusabarish/hugo-profile/blob/master/website/v3.yaml) as base template.
- You should have the mentioned images in static folder to use them. 
```
cd themes
git clone https://github.com/gurusabarish/hugo-profile.git
```

## Local Development
- Just clone this repo
- Now create config.yaml file in your root folder and use one of these [v1config](https://github.com/gurusabarish/hugo-profile/blob/master/website/v1.yaml), [v2config](https://github.com/gurusabarish/hugo-profile/blob/master/website/v2.yaml), [v3config](https://github.com/gurusabarish/hugo-profile/blob/master/website/v3.yaml) as base template.
- Run your folder using `hugo serve` commend
``` 
git clone https://github.com/gurusabarish/hugo-profile.git
cd hugo-profile
```

## Direct deployment 
- Fork this repo or create new repo using `use this template` button and connect repo to netlify.
- You can customize the config file, content and everything inside website folder. Netlify will automatically deploy your changes every time you modify the repo.

_Note: If these steps are not working then, provide your config.yaml or config.toml file's content along with details here._ 

If you liked this template, star this repo. It will motivates me. Thank you ❤️

**Comment by gurusabarish** [comment]
@josephjosedev , Hope! you got some idea.

Thanks ❤️ 
Gurusabarish
