### ISSUE TITLE
Clicking on a company that contains spaces does not show the details.

### ISSUE THREAD

**Issue by hyasuda** [gurusabarish/hugo-profile#23]
**Describe the bug**
If the "company" field in the "experience" field contains a company name with a space, clicking on the company name does not display the details.

**Screenshots**
![image](https://user-images.githubusercontent.com/20940835/129479246-f7dc964d-f5c6-40e0-89b2-017daa4811fc.png)
In this image, "Private Company" has been clicked. Normally, the details should be displayed on the right side, but the details of the company that was clicked on just before it was displayed are displayed.

**Desktop (please complete the following information):**
 - Hugo : hugo v0.87.0-B0C541E4+extended linux/amd64
 - Browser : Google chrome 92.0.4515.131

**Additional context**
Test site about this issue is [here](https://hyasuda.github.io/).

This is the first time for me to submit an issue. I'm sorry if you bother my this issue. Thanks in advance.

**Comment by gurusabarish** [comment]
hey @hyasuda 

I have updated, [find this](https://github.com/gurusabarish/hugo-profile/blob/75e1af431cb8c9d034f12b754ed971642c7a605c/website/config.yaml#L60). Use updated template to reflect the changes

Thank you for letting me know ❤️
