### ISSUE TITLE
Questions: Medium embedding, picture sizing, font colours

### ISSUE THREAD

**Issue by dailyprice** [gurusabarish/hugo-profile#24]
Thanks for creating this awesome template!

I am a big CSS/HTML noob and had a couple of questions:
1. is it possible to embed posts from my Medium page directly under the "Recent Posts" section (would have the navbar redirect to the Medium page)?
2. I cannot get the images in the project section to appear appropriately sized (currently they are getting stretched horizontally. I looked at the v3.css under the projects section, but cannot change any property to regulate this behaviour). I thought the `.bg-pro img` property would regulate this behaviour. But it does not seem to have an impact. Could you help me?
3. I am a bit confused about the color settings in the v3.css file, under the home section I do not find colour matching the bright yellow in the home section for the sentence "Hi there, I'm".

These are just questions, but hope you can help!

Many thanks.

**Comment by gurusabarish** [comment]
> is it possible to embed posts from my Medium page directly under the "Recent Posts" section (would have the navbar redirect to the Medium page)?

Currently, it is not available. 
> I cannot get the images in the project section to appear appropriately sized (currently they are getting stretched horizontally. I looked at the v3.css under the projects section, but cannot change any property to regulate this behaviour). I thought the .bg-pro img property would regulate this behaviour. But it does not seem to have an impact. Could you help me?
I am a bit confused about the color settings in the v3.css file, under the home section I do not find colour matching the bright yellow in the home section for the sentence "Hi there, I'm".

currently, I have no time to work on it. I may work soon for these features.

**Comment by gurusabarish** [comment]
> is it possible to embed posts from my Medium page directly under the "Recent Posts" section (would have the navbar redirect to the Medium page)?

@dailyprice I don't know, How to do that?

Any oss developers, please take a look
