### ISSUE TITLE
Can not load image from /images/*.png

### ISSUE THREAD

**Issue by phamdat09** [gurusabarish/hugo-profile#25]
Hello,

I use `v3.yaml` configure, but I can not load my image to website

Can u check it ??

**Comment by gurusabarish** [comment]
Where you want to add the image ?  Make sure, you use [this](https://github.com/gurusabarish/hugo-profile/blob/75e1af431cb8c9d034f12b754ed971642c7a605c/website/v3.yaml#L107) format.

Further, share your configuration detail for that image.

**Comment by gurusabarish** [comment]
@margaridalsemedo @thomasdpage Did you place your images inside your ```static/image``` folder? I saw that few people build their webpage without images.

If possible, please give your github repo url

**Comment by emze9** [comment]
Hi @gurusabarish,
I can't load images either. I've tried so many possibilities.

Thanks for advance.

**Comment by gurusabarish** [comment]
Hi @emze9, please give the details clearly

Anyone, Please provide the full details clearly. Like,
- Deployment plateform
- Is this not working both development and deployment?
- How you try to create your website? using Hugo themes, Using "use this template" and netlify, Using "use this template" and github pages
- Did you place the images inside your ```static/images``` folder ?
- And many more

**Comment by emze9** [comment]
I've just deploy with `static/images` into the root folder and it works. Like this:
```
.(site root)
├── config.yaml
├── static
│   └── images
│       └── <image>.png
└── themes
     └── hugo-profile
```

**Comment by gurusabarish** [comment]
You have to change the images inside root static folder
