### ISSUE TITLE
about CSS, PDF and achievements

### ISSUE THREAD

**Issue by annsopirate** [gurusabarish/hugo-profile#27]
Hello,
I use the v3.yaml configure, and I have some questions for you to ask.

- Is it possible to change the CSS ? I tried, but nothing updates...

- Is it possible to add a link to a PDF ? for example, in "about me" I would like to put my CV "click here to download my CV", but i dont know how to modify the YAML / HTML file. I tried with
<a href="test.pdf">Click here to download my CV !</a> 
but when I click on it, it opens a "404 page not found" page. In which directory should I store my PDF?

- Is it possible to make clickable the achievements ? I want to put a link that redirects to a site.

Thanks for the theme. I also have problems with images but I saw that you are already working on this.
Have a good day !

**Comment by gurusabarish** [comment]
Hi @annsopirate,

>Is it possible to change the CSS ? I tried, but nothing updates...
   Is it possible to make clickable the achievements ? I want to put a link that redirects to a site.
   Is it possible to add a link to a PDF ? for example, in "about me" I would like to put my CV "click here to download my CV", but i dont know how to modify the YAML / HTML file. 

I will add these features soon

> I also have problems with images but I saw that you are already working on this.

Did you place the images inside ```static/images``` folder?
If possible, please share github repo url that would be much helpful to fix

Thank you,

**Comment by annsopirate** [comment]
Hi,

Thanks. I make my portfolio for the university. I have to finish it for January.

Here is the link of my github repo : https://github.com/annsopirate/mon-portfolio !
I tried several things in the config.yaml (Projects part) but nothing works. Maybe my project is badly organized... ^^'. It's my first Hugo project.

Thank you for your answer 😊

**Comment by gurusabarish** [comment]
hi @annsopirate, [This is project structure](https://github.com/gurusabarish/hugo-profile/issues/25#issuecomment-962115752)

You should have all images inside root's ```static/images``` and you can use them as below.
```yaml
- name: "Example project without details"
  img: /images/project.jpg # you should have the static/images folder in root.
  githublink: "https://github.com/"
  featuredlink: "/"
  description: "Description of project"
```

Thanks,

**Comment by gurusabarish** [comment]
Hii @annsopirate 

> Is it possible to change the CSS ? I tried, but nothing updates...

You can. Just make [this](https://github.com/gurusabarish/hugo-profile/blob/a39edbe3531e137ad7ae3c328b28f46a97571ae7/website/v3.yaml#L22) to true and create a file called style.css inside static folder. Now, write your css code in the file. It will reflect in website.

>  Is it possible to make clickable the achievements ? I want to put a link that redirects to a site.

You can. [Find this](https://github.com/gurusabarish/hugo-profile/blob/a39edbe3531e137ad7ae3c328b28f46a97571ae7/website/v3.yaml#L121)

Thank you

**Comment by annsopirate** [comment]
Hi,

Thanks for the images and for the achievements. It works !!!!

For the CSS, I added the "customCSS: true" (customCSS wasn't already in the .yaml, so I added that line).
I created a style.css in the static folder but when I try to change the color of my name in the home part, it doesn't work. Maybe because the color of the name is in a bootstrap.min.css file? Can we modify that kind of file? Or maybe I have to put the style.css file in static/css folder?
I can't even modify the darkmode...

Sorry for all my problems...😅
Thank you for your help !!

**Comment by annsopirate** [comment]
Hey, I'm back !!

I fixed the CSS problem, it was because of the cached images and files. I had to clean it to see the changes.
Now I have a new question ! In theme demo we can see a "know more" button in the projects section, but I can see the properties for this button in the code. I need it because when I put the site in phone mode, the texts exceeds the blocks.

Thanks again !!!!

**Comment by gurusabarish** [comment]
Hi @annsopirate 
Sorry, I couldn't get you. could you elaborate with screenshot?

Thank you

**Comment by annsopirate** [comment]
Hello !

I'm talking about that button (first image)
I don't know how to get it.
![image1](https://user-images.githubusercontent.com/93653176/144325899-c07661d8-f3b1-42e0-bb17-1613aad5dd8c.PNG)

I need this button because when I choose a smartphone format, we can see that the text overflows (second image)
![image2](https://user-images.githubusercontent.com/93653176/144325902-bc240e28-32c9-467d-94dc-abdedbf86e48.PNG)

Thanks for your help !!

**Comment by gurusabarish** [comment]
Hii @annsopirate 

If you want the button, just create a folder called project inside content folder. There you can create your projects.

Reference: https://github.com/gurusabarish/hugo-profile/blob/master/website/content/project/example.md

I will look forward the text overflow

Thanks

**Comment by annsopirate** [comment]
Thanks for your help !!
