### ISSUE TITLE
Credly icon to profession

### ISSUE THREAD

**Issue by kvandenbrande** [gurusabarish/hugo-profile#31]
Hi, is it possible to add the Credly icon like LinkedIn as options to profession? 
https://www.credly.com, it's a place where for example you can provide your ISACA certificates.

**Comment by gurusabarish** [comment]
Hii @kvandenbrande 
>Hi, is it possible to add the Credly icon like LinkedIn as options to profession?
https://www.credly.com, it's a place where for example you can provide your ISACA certificates.

Added custom icon feature, refer [here](https://github.com/gurusabarish/hugo-profile/blob/f279e15318144b36f695c73f90cbf277442743f6/website/v3.yaml#L45)

Thank you

**Comment by kvandenbrande** [comment]
Thx mate!

________________________________
