### ISSUE TITLE
Question: Can dark mode to be set on auto?

### ISSUE THREAD

**Issue by abe-101** [gurusabarish/hugo-profile#39]
I'd like it that when someone visits my site and their OS/Browser is set to dark mode the website should reflect that and they shouldn't have to toggle it

**Comment by gurusabarish** [comment]
Hi @abe-101, 

Follow #37 - @lr1980 working on that
Thanks

**Comment by abe-101** [comment]
Thanks for the quick response
I really like this theme just got my site running at [habet.dev](https://habet.dev)
Another thing about dark mode is it doesn't seem to work on blog posts

**Comment by gurusabarish** [comment]
> I really like this theme just got my site running at habet.dev. Another thing about dark mode is it doesn't seem to work on blog posts

Sounds good.
Dark mode is very light for blog posts. I will look into it.

**Comment by abe-101** [comment]
k, thank you
one last question, i used your template on github and the gihub actions does all the deploying, its pretty neat. Question though is how will i upgrade when you make fixes? My site is a repo that's completely separate

**Comment by gurusabarish** [comment]
> how will i upgrade when you make fixes? My site is a repo that's completely separate

I don't know 'how to automate this'. For now, we could upgrade manually by cloning the repo for each update or upgrade

**Comment by abe-101** [comment]
> > how will i upgrade when you make fixes? My site is a repo that's completely separate
> 
> I don't know 'how to automate this'. For now, we could upgrade manually by cloning the repo for each update or upgrade

I purposed a salutation in in this pull request https://github.com/gurusabarish/hugo-profile/pull/41

**Comment by gurusabarish** [comment]
> I'd like it that when someone visits my site and their OS/Browser is set to dark mode the website should reflect that and they shouldn't have to toggle it

Added in #45
