### ISSUE TITLE
Stable version 4

### ISSUE THREAD

**Issue by gurusabarish** [gurusabarish/hugo-profile#42]
Now, the current template has 3 variants in a single template. It may take some extra time to build your site.

# stable version 
I wanted to make this template clean and stable. So, I proposed a solution,
- I noticed that, V3 and v2 are mostly used by many people. 
- So, The **V1 will be removed in the future version**
- And V2 will be released as a separate template from V3.3
- Finnaly, V3 alone will be maintained here
 
# features
- Bootstrap 5
- Dark mode
- Customizable colors

**Suggest features you want to add.** Please, share your opinion for making a better version.

**Comment by gurusabarish** [comment]
### Here after, V2 will be maintained here
- V2 is [Here](https://github.com/gurusabarish/HugoProfileV2)

_Note_:  ```V1 will be removed further```

**Comment by lr1980** [comment]
I added a time calculation (here: https://github.com/lr1980/hugo-profile/commit/1a6331cf62c0a95be3025f5e64cdaff30b6e4643)

```yaml
  experience:
    - company: "Google"
      role: "Software developer"
      startdate: 2021-02-01
      enddate: now
```

![Screenshot 2022-01-25 at 19 48 51](https://user-images.githubusercontent.com/1901770/151039946-82c7f6c7-fa10-4504-a52f-bb832a3efe0d.png)

But this commit on my fork based on other changes (e.g.: https://github.com/gurusabarish/hugo-profile/pull/38)
