### ISSUE TITLE
Drop-down menus in V3

### ISSUE THREAD

**Issue by torvenkat** [gurusabarish/hugo-profile#44]
It will be great to have drop-down menus in V3 of this great theme.  Also please consider way to add individual pages to the navigation menu easily.  Thanks.

**Comment by gurusabarish** [comment]
Hii @torvenkat,
- Dropdown added, [refer this](https://github.com/gurusabarish/hugo-profile/blob/00c24c1e15e6c6e6a9d1b8b31a0df16630548574/website/config.yaml#L21) to implement

>  Also please consider way to add individual pages to the navigation menu easily

you can add individual pages by creating `.md` files inside `content` folder

![image](https://user-images.githubusercontent.com/53465361/151802192-8148bb5c-7fb2-44c0-80e8-e73ca39d4f16.png)

**Comment by torvenkat** [comment]
Works perfectly.  Thanks for implementing this.  Much appreciated.
