### ISSUE TITLE
Make a Project post also a blog post?

### ISSUE THREAD

**Issue by abe-101** [gurusabarish/hugo-profile#49]
Hey
Thanks again for this awesome theme!
Can you direct me how i can make a project post also come up in the blog posts?

**Comment by gurusabarish** [comment]
>  Can you direct me how i can make a project post also come up in the blog posts?

I assume that, you are taking about [footer](https://github.com/gurusabarish/hugo-profile/blob/00c24c1e15e6c6e6a9d1b8b31a0df16630548574/layouts/partials/sections/v3/footer.html#L7). Replace this line as you want. Referance: https://geekthis.net/post/hugo-posts-from-multiple-sections/

```
{{ range first 5 (where .Data.Pages "Section" "in" (slice "tutorial" "news")) }}
	{{ .Title }}
{{ end }}
```

**Comment by abe-101** [comment]
Allow me to explain. In my content folder there is a folder called blog and projects. all md files in project land on the home page with a link to the write up at www.example.com/project. All files in blog end up in the blog sections at www.example.com/blog

what I'd like is for all project write ups to also end up as blog posts. logically it makes sense, cause a write up about a project is worthy of being a blog post...

**Comment by gurusabarish** [comment]
This is a [general template](https://github.com/gurusabarish/hugo-profile/tree/master/layouts/_default) for all pages like project and blog.

> what I'd like is for all project write ups to also end up as blog posts. logically it makes sense, cause a write up about a project is worthy of being a blog post... 

If you want to edit, just add blog folder(name as in your folder inside content folder) inside layouts like [this](https://github.com/gurusabarish/hugo-profile/tree/v3-stable/layouts/blogs) and paste the files of  `_default` folder there and replace [this line](https://github.com/gurusabarish/hugo-profile/blob/00c24c1e15e6c6e6a9d1b8b31a0df16630548574/layouts/_default/list.html#L25) in `blog folder`.

```
{{ range (where .Site.RegularPages "Type" "in" (slice "blog" "project") ) }} 
```
