### ISSUE TITLE
Few questions

### ISSUE THREAD

**Issue by rajganeshp** [gurusabarish/hugo-profile#5]
1) Is it possible to change the font?
2)  I want to embed a snippet of my "newsletter" from substack in the footer. Is it possible to embed code?
3) in the section, "Things I do" - Is it possible to change the icons? And more things. 
4) In the blog, how to show "short description". the description attribution is not showing anywhere
5) Is headings supported? I used various headings in MD file like ####, ### for various subheadings, but when it's converted, it's not displaying the headings. Is there any way to use headings?

**Comment by gurusabarish** [comment]
Hi @rajganeshp ,
I pushed some updates now with the [v2.1.0](https://github.com/gurusabarish/hugo-profile/releases/tag/v2.1.0). Please download the latest release to use the below.

> I want to embed a snippet of my "newsletter" from substack in the footer. Is it possible to embed code?

Yes, you can add embedded code using **embed** option in config file. Customize the code's width and height for better look and don't use the styling of your embed. 
**note**: If you use styling in embedded code, then don't use hashtag in embed's background color.(it is considered as a comment in config file) Please use the rgp format.

> in the section, "Things I do" - Is it possible to change the icons? And more things.

Yes, you can add font awesome icons with its class name as [here](https://github.com/gurusabarish/hugo-profile/blob/6d50a08863a04f310826c13e048303352c3183e7/exampleSite/config.yaml#L42) and you can also add more items like [this method](https://github.com/gurusabarish/hugo-profile/blob/6d50a08863a04f310826c13e048303352c3183e7/exampleSite/config.yaml#L39).

> In the blog, how to show "short description". the description attribution is not showing anywhere

Description to get a better seo. You can also show your description in your blog post with showdescription option in config file as [here](https://github.com/gurusabarish/hugo-profile/blob/6d50a08863a04f310826c13e048303352c3183e7/exampleSite/config.yaml#L58)

> Is headings supported? I used various headings in MD file like ####, ### for various subheadings, but when it's converted, it's not displaying the headings. Is there any way to use headings?

Now I updated these all. It will looks like [here](https://hugo-profile.netlify.app/blog/markdown). But, h1(#) and h2(##) is preferable for heading.

> Is it possible to change the font?

This theme's fonts are looking awesome. So, I don't think as of now

**Comment by rajganeshp** [comment]
Thanks for quick response. Can you update you Readme to show how to pull
latest updates? I'm not too familiar with Git.

**Comment by rajganeshp** [comment]
Can you show me how to embed the code?

I figured out how to get the latest code.

**Comment by gurusabarish** [comment]
>Can you show me how to embed the code?

- Go to your Substack account and copy the embedded code. It looks like below image.

![substack](https://user-images.githubusercontent.com/52481812/97067554-eb061e80-15db-11eb-9e58-207aa0bb78b4.PNG)

- Come back to the config file and paste your code as below without styling. If you want customize the height and width, then change it with your embed's width and height.
```yaml
....
Params:
    .....
    #footer
    embed: <iframe src="https://gurusabarish.substack.com/embed" width="480" height="320" ></iframe>
```

**Comment by rajganeshp** [comment]
Is it working for you? It's not working for me when I tried your above
snippet. Also, the "blog summary is not working.

Thanks,
Raj

**Comment by gurusabarish** [comment]
>Is it working for you? It's not working for me when I tried your above

Its not working now. It will take some time to fix. I will notify you when I did.

> blog summary is not working

It works well as the image. Do you use the [showdescription](https://github.com/gurusabarish/hugo-profile/blob/6d50a08863a04f310826c13e048303352c3183e7/exampleSite/config.yaml#L58) option's value as true?
 
![description](https://user-images.githubusercontent.com/52481812/97088744-9b156f00-1650-11eb-9c33-e05b4bca9c1c.PNG)

**Comment by rajganeshp** [comment]
no problem. thanks. On the blog summary, it will be nice to show on the
listing page.. so we can give few lines on what the blog is about.

**Comment by gurusabarish** [comment]
> no problem. thanks. On the blog summary, it will be nice to show on the
listing page.. so we can give few lines on what the blog is about.

Can I pull your website code with all your customization in your github repo? If you open to pull the code, then tell me your needs and the github repo link.

I can mail the full source code after making the website for the maintenance purpose.

**Comment by gurusabarish** [comment]
Hi @rajganeshp ,
I have updated the description as you said. 

Thanks

**Comment by rajganeshp** [comment]
Thanks. Will check it out.

**Comment by rajganeshp** [comment]
it's working
