### ISSUE TITLE
Can't parse header.html

### ISSUE THREAD

**Issue by Gomusss** [gurusabarish/hugo-profile#55]
**Describe the bug**
themes/hugo-profile/layouts/partials/sections/header.html:51:1": parse failed: template: partials/sections/header.html:51: unexpected unclosed action in command

After cloning repo and following the steps to install a theme I noticed errors related to header.html
I added to config.toml a line with the theme, tried to change config.toml to config.yaml but with no luck
The error occurs on vps, didn't check netlify 

**To Reproduce**
1. Git clone repo to root directory
2. Edit config.yaml with adding the theme
3. run hugo and notice the error

**Comment by igna-v** [comment]
Hi,

You should modify the if sentences in the file (partials/sections/header.html)

From:
 {{
 if and
 (.Site.Params.about.enable | default false)
(not (.Site.Params.navbar.menus.disableAbout | default false))
}}



To:
{{ if and (.Site.Params.about.enable | default false)  (not (.Site.Params.navbar.menus.disableAbout | default false))  }}

(so delete new lines)

That worked for me, hope it helps

**Comment by gurusabarish** [comment]
>  {{ if and (.Site.Params.about.enable | default false) (not (.Site.Params.navbar.menus.disableAbout | default false)) }}

Hi @Gomusss, hope it works. Thanks @igna-v

**Comment by Gomusss** [comment]
Hi,
It works like a charm.
There were more same issues in that file, but removing unnecessary spaces resolved all issues.
Thanks a lot
