### ISSUE TITLE
Make "Things I Do" cards link-able

### ISSUE THREAD

**Issue by dombraccia** [gurusabarish/hugo-profile#56]
I really like this theme for personal websites. I like the "Things I do" cards, but I think they would be even cooler if you could link something to them to send people to either other parts of the content on the site or to another URL where I have some content. 

Let me know if you need any more info or screenshots for what I mean. I appreciate it!

**Comment by gurusabarish** [comment]
Hii @dombraccia , I moved the V2 to separate repo. You can check them [here](https://github.com/gurusabarish/HugoProfileV2) 

> I like the "Things I do" cards, but I think they would be even cooler if you could link something to them to send people to either other parts of the content on the site or to another URL where I have some content.

It was already added there. 
- [`config.yaml`](https://github.com/gurusabarish/HugoProfileV2/blob/547f38a1b40b55d511f48d4ca522deb2e90b01f8/exampleSite/config.yaml#L87)
- [demo](https://hugo-profile-2.netlify.app/)
