### ISSUE TITLE
any way to put image in blog summary?

### ISSUE THREAD

**Issue by harshnandwana** [gurusabarish/hugo-profile#62]
1.if i keep light mode as default than anytime i move to new page even if i change my mode to dark it gets refreshed to light mode
2. is there anyway to turn of social in blogs
3. is there any way to put image in blog summary

**Comment by sourabhdeshmukh** [comment]
1. Your default settings are set to light, which might be why it is returning to light view.
2. You can customize the layout configuration by adding conditions or changing the default config to false.
3. You can add the images in the blog files themselves. You can follow the markdown syntax for that. https://www.markdownguide.org/basic-syntax/#images

**Comment by Liu22Yi** [comment]
I also have problem on  putting image in blog summary. Now we can see recent posts in the homepage with plain text in the homepage. Can we display the pictures as well?

**Comment by gurusabarish** [comment]
> Now we can see recent posts in the homepage with plain text in the homepage. Can we display the pictures as well?

As of now, this is not available. I will add this in future updates.

**Comment by gurusabarish** [comment]
> As of now, this is not available. I will add this in future updates.

@harshnandwana @Liu22Yi Added this functionality fdd628c9cd5df376e85fefc4f0d1b0219bc910bb
