### ISSUE TITLE
Blogs - flickers when loading more

### ISSUE THREAD

**Issue by IdiosApps** [gurusabarish/hugo-profile#63]
**Describe the bug**
Flickering blog page

**To Reproduce**
Go to Blogs demo page https://hugo-profile.netlify.app/blogs/ and click 2/ > / >>. It refreshes and goes to https://hugo-profile.netlify.app/blogs/page/2/, which flickers

**Expected behavior**
No flicker 

**Desktop (please complete the following information):**
windows 11, chrome

**Comment by HugoSave** [comment]
Hmm, mine does not flicker on Mac OS on Chrome or Safari. 

What flickers? The blog cards or the whole page? Is it a continous flicker?

I guess you can reproduce by just going to [https://hugo-profile.netlify.app/blogs/page/2/](url) and refresh the page directly too?

Do you have any more details?

**Comment by IdiosApps** [comment]
![Animation](https://user-images.githubusercontent.com/12559216/179075578-cbba64f5-e6a1-45ef-9a27-a7ab601996b3.gif)

Here is a gif. There was 1 smooth transitions, then a few flickering ones. 
It's the whole page. A short flicker. 
I guess it's reloading the page and just shows the background for a short moment

**Comment by IdiosApps** [comment]
It's better on Edge. My chrome is `Version 103.0.5060.114 (Official Build) (64-bit)`

**Comment by IdiosApps** [comment]
Good suggestion. I throttled to 550KB/s and 30ms ping, and the page sometimes has the full-white until the highlighted circle time
![image](https://user-images.githubusercontent.com/12559216/179087654-10ebf5f1-e6b0-4466-a18a-b8b8b03f0400.png)

**Comment by IdiosApps** [comment]
Some observations about [the google font that loads](https://fonts.googleapis.com/css2?family=Alata&family=Lora:ital,wght@0,400;0,500;0,600;0,700;1,400;1,500;1,600;1,700&family=Roboto:ital,wght@0,100;0,300;0,400;0,500;0,700;0,900;1,100;1,300;1,400;1,500;1,700;1,900&display=swap)

Fonts are loaded through [CSS](https://github.com/gurusabarish/hugo-profile/blob/master/static/css/font.css) it seems.
I see that Lora has 40 font-families, including vietnamese and cyrillic etc. Is this content-aware, so we're only loading uniode ranges that are displayed in the website?

This link says that calling from CSS wastes time compared to calling from HTML head. https://sia.codes/posts/making-google-fonts-faster/#warm-up-that-connection-faster-with-preconnect

Somewhat similar to preload, apparently google fonts suggests to use preconnect. It does connection handshake earlier, so actual communication later has no startup time. https://sia.codes/posts/making-google-fonts-faster/#warm-up-that-connection-faster-with-preconnect. I tried to get Lora from [google fonts](https://fonts.google.com/specimen/Lora) this way, but it only has "Download family" which downloads a zip.

Can we validate if it's slow font loading by only loading defaults? (Roboto)

**Comment by HugoSave** [comment]
That was a great image, good that you found at what point in time the page looks fine. 

Hopefully we can remove some latency just by moving down the script tag which from your image seems to be the biggest bottleneck at the moment. After that the bootstrap css might be the bottleneck.

Then we should maybe try using CDN bootstrap instead of serving it ourselves. (Have a config that enables both options would be preferable). I guess what is best depends on where you host it and where your clients are. 

Yeah I'm not sure about how caching works completely. But it feels it might be cached more often if taken from a cdn source which the browser suspects can be used on multiple websites? Worth a shot at least.

**Comment by IdiosApps** [comment]
![image](https://user-images.githubusercontent.com/12559216/179092494-21844274-5997-43e6-b583-c2af525b7aef.png)

`preconnect` to fonts.gstatic does indeed sound useful. 
Even if we ask to `preload` the fonts, it will have to talk to google to get CSS first, then talk to fonts.gstatic for woff. 
By the time it is ready to ask for the .woff, it should be set up ready to talk to fonts.gstatic.
Maybe we should try both. Try to loads css early, then be ready to talk about woff early

**Comment by IdiosApps** [comment]
Btw I'd love to see the commits/PRs for these to see how you approach them. 

BTW, I came across another Hugo template earlier: [digital-garden](https://themes.gohugo.io/themes/hugo-digital-garden-theme/). _It made me question the "reload the page when selecting next blogs" approach_. I expect here they shot a lot of blogs then let you filter. I don't know how it is for e.g. 50+ blogs. [Digital garden demo blog page](https://hugo-digital-garden-demo.netlify.app/garden/). 

Is it possible to use something like a CSS carousel over all data and just use the titles+links to blog posts, so no page load is needed? If there's no page reloads, that would fix the problem too

**Comment by HugoSave** [comment]
Yes that would kinda fix the problem in this particular case. But you would still see this flickering each time you refresh the site and we might get more google-page-speed score on all pages of the site if we can reduce the loading time a bit. But sure that would be a valid option for the blog disaply mechanism that probably would provide a slightly more smooth experience. 

I'll probably test some things out this weekend and hopefully make a new issue with some proposals.

**Comment by IdiosApps** [comment]
https://google-webfonts-helper.herokuapp.com/fonts/lora?subsets=latin "easy" way to locally host the fonts. Don't need to think about preload/preconnect if doing that
