### ISSUE TITLE
Search box

### ISSUE THREAD

**Issue by AndreaPaolo** [gurusabarish/hugo-profile#66]
Hi, I've been using this template for a couple of days. In the blog section it would be interesting to have a small search box in order to facilitate the search for articles.

#### This text is translated by google translator from Italian to English. Below I leave the original language version.
Sto usando questo template da un paio di giorni. Nella sezione blog sarebbe interessante avere una piccola search box così da facilitare la ricerca degli articoli.

**Comment by gurusabarish** [comment]
Will look into that, when I am free.

**Comment by gurusabarish** [comment]
@AndreaPaolo  added search box in 80e9a7971b401c658cac958bd2b06ac5df626493
