### ISSUE TITLE
Need help with hosting pages in github.

### ISSUE THREAD

**Issue by sambidwasti** [gurusabarish/hugo-profile#69]
I was not sure where to ask question so i am posting it here. 

I am having trouble hosting the website on github. I see the content but all the element from themes are missing. I am not sure what i am doing wrong. Locally, i can see my webpage. My first guess was the baseURL but i have tried "/", https*, http*, etc and still having the issue. 

Any help is appreciated.

Repo: https://github.com/sambidwasti/blog1
Page: https://sambidwasti.github.io/blog1/

**Comment by sambidwasti** [comment]
Additional notes: I created a fork and used demo branch and i can see the page. I am trying to compare files in the demo with files in the gh-pages branch. 

- Is that correct comparison i should be making?

**Comment by sambidwasti** [comment]
I think i resolved the issue. It was caused by some pathing issue. Which made that the local server was good but the index.html when used hugo was giving issue. The difference in pathing issue and some additional information on URL management, specifically Canonicalization (canonifyURLs) are in the following two links. 

https://github.com/gohugoio/hugo/issues/8078
https://gohugo.io/content-management/urls/

**Comment by sambidwasti** [comment]
I forgot to mention, i resolved it by adding 
`canonifyURLs: true `
in my config.yaml

**Comment by Prakash4844** [comment]
Thanks 

```yaml
canonifyURLs: true 
```
worked

Previously i had tried 

```yaml
relativeURLs = true
uglyURLs = true
```

Which made the Homepage load correctly but could not load Blog Pages.

This only needs to be done  on Github Pages and not on Netlify.
Netlify Works by Default.
