### ISSUE TITLE
Give option to remove instagram, twitter, etc

### ISSUE THREAD

**Issue by rajganeshp** [gurusabarish/hugo-profile#7]
Though I know how to edit the template, it'll be nice if you give an option to remove the social links. I don't use Instagram, so I don't want to display it.

Also, some color options for "Things I do" will be great. 

Thanks,
Raj

**Comment by gurusabarish** [comment]
I pushed the code to disable social icons. So, **please use the latest.**
- To disable Instagram icon, leave Instagram as empty in your config file.
- Now, the color options are not available. It may come in future updates. I will notify you when its come.
