### ISSUE TITLE
Rss for blog feed

### ISSUE THREAD

**Issue by abe-101** [gurusabarish/hugo-profile#71]
**Is your feature request related to a problem? Please describe.**
Does the blog include a rss feed?

**Describe the solution you'd like**
If not is it easy to implement?

**Comment by MichalLauer** [comment]
Hi, the RSS feed is by default under _example.com/index.rss_

**Comment by gurusabarish** [comment]
> Hi, the RSS feed is by default under example.com/index.rss

@MichalLauer, @abe-101 actually default url is ```example.com/index.xml```
