### ISSUE TITLE
TOC missing in .Rmd

### ISSUE THREAD

**Issue by MichalLauer** [gurusabarish/hugo-profile#73]
**Describe the bug**
.Rmd files do not have TOC generated, but .md files do.

**To Reproduce**
1. Create sample Hugo project with this template
2. Create .Rmd file in _content/post_ or _content/blogs_
3. Generate site
4. See no TOC

**Expected behavior**
There should be a TOC generated from the file structure.

**Screenshots**
Generated website (modified to .Rmd)
![image](https://user-images.githubusercontent.com/20439350/189525129-d8f9205f-6c2d-4e51-93a1-74ae2cb0966d.png)
yaml header
![image](https://user-images.githubusercontent.com/20439350/189525155-5757f768-e947-41ce-9bc7-967c4e67a37d.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 105.0.5195.102

**Comment by gurusabarish** [comment]
Hii @MichalLauer , try to add `toc: false` instead of `toc: null`

**Comment by MichalLauer** [comment]
Hi,

after some googling it's not a template issue but hugo/blogdown issue. I needed to specify HTML output, not .md output:)
