### ISSUE TITLE
navbar and breadcrumb is not working properly in sub directories

### ISSUE THREAD

**Issue by rajganeshp** [gurusabarish/hugo-profile#8]
1) I have only following lines. But it shows facebook and instagram. 
2) when I go inside blog, the home button is not taking me to home page using the breadcrumb. I would like to work when I click on the logo as well. I thought it used to work before. 

  # social
  name: "Raj Pandurangan"
  github: "https://github.com/rajganeshp"
  linkedin: "https://linkedin.com/in/rajganeshp"
  twitter: "https://twitter.com/rajganeshp"

**Comment by gurusabarish** [comment]
If you dont want use, then leave those empty.
```
instagram: ""
facebook: ""
```

**Comment by rajganeshp** [comment]
Okay that worked. So only the HOME button is not working.

**Comment by gurusabarish** [comment]
Did you make the menus as below ? Please comment your config file's content here.
```
customMenus:
  - name: "Blog"
    Url: "/blog"

  - name: "Course"
    Url: "/course"
```

**Comment by rajganeshp** [comment]
that's working. So if you go to any blog, you see a breadcrumb like "/home
/blog /redeam. When I click on home from that blog, it's not going to home
page

**Comment by gurusabarish** [comment]
I can understand your problem. Hugo-profile's [demo site]( https://hugo-profile.netlify.app) is working properly. So, there is no problem in theme.
- That's why I asked your config file's content. Could you provide?

I can help you to fix.

**Comment by rajganeshp** [comment]
thanks for your support. Attached my config here.

**Comment by gurusabarish** [comment]
There is no file or link attached. Please check it out.

**Comment by rajganeshp** [comment]
ubaseURL: "https://connectthoughts.com"
languageCode: "en-us"
title: "Connecting Thoughts"
theme: "hugo-profile"

googleanalytics: UA-177822716-1
Paginate: 8

taxonomies:
  tag: "tags"
  category: "categories"

params:
  favicon: "/images/logo-raj.png"
  description: "A high performance hugo theme for personal website. It is
single page portfolio. It has blog."
  copyright: "2020"

  # Navbar Menus
  customMenus:
  - name: "Blog"
    Url: "/blog"
  - name: "Course"
    Url: "/course"

  # social
  name: "Raj Pandurangan"
  github: "https://github.com/rajganeshp"
  linkedin: "https://linkedin.com/in/rajganeshp"
  twitter: "https://twitter.com/rajganeshp"
  instagram: ""
  facebook: ""

  usedothings: true
  Things:
    - logo: fab fa-python
      title: Python
      description: I build something beautiful using Python.

    - logo: fas fa-robot
      title:  Machine learning
      description: I train robust models for various tasks.

    - logo: fab fa-html5
      title: Things for web
      description: I love to build things for web

    - logo: fa fa-cloud
      title: Things for web
      description: I love to build things for web

  # About
  profile_image: "/images/profile.jpg"
  descripe_l1_person: "I’m a capable Presales architect who can act as the
glue that links together mission critical security requirements. Articulate
and effective communicator who has a history of developing products that
push the limits of technology. Able to respond to the ever changing demands
of clients by creating innovative high quality and defect-free security
solutions that precisely meet their business needs. Strong management and
methodical aptitude with an innate ability in decision-making, coordinating
and synthesizing data."
  descripe_l2_person: ""
  job: "Cybersecurity Specialist"
  resume: "/about"

showdescription: true

embed: <iframe src="https://connectthoughts.substack.com/embed" width="360"
height="200" ></iframe>

Author:
  name: "Rajganesh Pandurangan"
  website: "https://github.com/rajganeshp"

**Comment by gurusabarish** [comment]
Okay thanks for your content. I will check and let you know.

**Comment by gurusabarish** [comment]
Thanks for reporting this issue. 

Sorry @rajganeshp , It was here because of the theme's bug. Now, I fixed both breadcrumb and home button.
Find the new updated code and try it.

**Comment by rajganeshp** [comment]
it worked. thanks for quick response.

I'm good with the template now. simple for my needs.
