### ISSUE TITLE
Inability to customize the Recent Posts partial

### ISSUE THREAD

**Issue by artis3n** [gurusabarish/hugo-profile#82]
The Recent Posts filter only works if the content exists under a `/content/blogs` directory because `blogs` is hard-coded into it.

https://github.com/gurusabarish/hugo-profile/blob/efc0918ad7e4d8d929e70a2c6478ad4cac99a467/layouts/partials/sections/footer/recentBlogPosts.html#L6-L8

This value should be a variable and pulled by something in the `config.yaml` file. For example, I placed my content under `/content/blog` and so Recent Posts was broken for a non-obvious reason.

Ideally (although a different problem), I have multiple folders under `/content` and Recent Posts should grab the most recent pages from any of them. For example, I have `/content/blog` and `/content/writeups`. But, Recent Posts will only display the content from `/content/blog` (once I change the hard-coded value).

Lastly, I'd like Recent Posts to show up on my home page but not on the specific `/content/blog` (or `/content/writeups`) pages. I don't see a way to configure that currently, it seems all or nothing, leading me to disable it altogether. Am I missing something?

**Comment by artis3n** [comment]
Also, `first 3` reminds me, it seems the `Paginate` variable listed in the example `config.yaml` doesn't actually do anything? I didn't see a location on the theme where the number of items listed changed when that variable changes - I think 3 is hard-coded everywhere.

This theme is beautiful and great to use, I just have some questions as I get used to it! :D

**Comment by gurusabarish** [comment]
Added support for this, [refer here](https://github.com/gurusabarish/hugo-profile/blob/b783b1b224f03040127e204fa69e1999185855d5/exampleSite/config.yaml#L339)
```
footer:
    recentPosts:
      path: "blogs"
      count: 3
      title: Recent Posts
      enable: true
      disableFeaturedImage: false
```

**Comment by artis3n** [comment]
That's awesome, thanks!
