### ISSUE TITLE
Google Analytics Configuration

### ISSUE THREAD

**Issue by vdinolov** [gurusabarish/hugo-profile#86]
Wondering if anyone else has had an issue configuring GA tracking. I have created a `googleAnalytics` field in the `config.yml` file and added my tracking id (`googleAnalytics: G-MEASUREMENT_ID`). I am not receiving any data on my site traffic via GA. Is there something I am missing like adding a script to `head.html` or `baseof.html`? @gurusabarish

**Comment by gurusabarish** [comment]
Hi @vdinolov , Did you follow like [this](https://github.com/gurusabarish/hugo-profile/blob/a15bcb669966e531b44207ff4c388bdbb6d260bb/exampleSite/config.yaml#L17) ?

**Comment by vdinolov** [comment]
Hi @gurusabarish - thanks for the response! I tried that and unfortunately still not working.
```
Paginate: 3
enableRobotsTXT: true
googleAnalytics: UA-212854371-1 
```

 To double check, I used both the `UA_id` and `measurement_id`. I also accessed my site from a different browser and turned off security settings just in case (Safari will block google analytics tracking).

There is a step in the GA platform about copy and pasting the global site tag: 

```
<!-- Google tag (gtag.js) -->
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-212854371-1"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-212854371-1');
</script>
```

> This is the Global Site Tag (gtag.js) tracking code for this property. Copy and paste this code as the first item into the <HEAD> of every webpage you want to track. If you already have a Global Site Tag on your page, simply add the config line from the snippet below to your existing Global Site Tag.

**Is this necessary or does the template take care of this?**

**Comment by vdinolov** [comment]
I looked at some other themes and they sometimes include a partial `analytics.html` or include the Google tag in the script. Here are some examples:

[copy paste into html](https://github.com/adityatelange/hugo-PaperMod/discussions/248)
[partial method 1](https://github.com/luizdepra/hugo-coder/blob/0bdf2500ae543145ed2a34a7c4af72e5fe4d0075/layouts/partials/analytics/googletagmanager.html)
[partial method 2](https://github.com/chipzoller/hugo-clarity/blob/1d7940986aafdaa08e71e251fc1714dd88fda650/layouts/partials/analytics.html)

Has GA worked for you in testing?

**Comment by gurusabarish** [comment]
> Has GA worked for you in testing?

@vdinolov It's working fine. I am using analytics for [demo site](https://hugo-profile.netlify.app/)

> I looked at some other themes and they sometimes include a partial analytics.html or include the Google tag in the script. Here are some examples:
https://github.com/adityatelange/hugo-PaperMod/discussions/248
[partial method 1](https://github.com/luizdepra/hugo-coder/blob/0bdf2500ae543145ed2a34a7c4af72e5fe4d0075/layouts/partials/analytics/googletagmanager.html)
[partial method 2](https://github.com/chipzoller/hugo-clarity/blob/1d7940986aafdaa08e71e251fc1714dd88fda650/layouts/partials/analytics.html)

Will add them in future release

**Comment by vdinolov** [comment]
> @vdinolov It's working fine. I am using analytics for [demo site](https://hugo-profile.netlify.app/)

I must be doing something wrong then...can you share your config for the demo site with GA configuration? I still don't have any data :(
