### ISSUE TITLE
Support for MathJax (Latex style Math equation) in blogpots markdown files 

### ISSUE THREAD

**Issue by inarighas** [gurusabarish/hugo-profile#99]
**Describe the bug**
`Hugo serve` does not render properly equations written using Markdown math commands in some blog posts.

**To Reproduce**
$$\left(1-\sum^{p'}_{i=1}\alpha_i~L^i\right)~X_t = \left(1 + \sum^q_{i=1} \theta_i~L^i \right)~\varepsilon_t$$

**Expected behavior**
![image](https://user-images.githubusercontent.com/14874638/216953320-8c7e5021-aea2-49bc-bf85-9d7c43896de6.png)

**Comment by inarighas** [comment]
This answer (https://stackoverflow.com/a/68506928/9360793) worked for me. I needed to add shortcode definition in my custom `layouts` folder and two lines in my custom `head.html`.

However, using `{{< mathjax/block >}}` each time I want to write an equation seems heavy. It does the job perfectly though...

**Comment by artis3n** [comment]
I think this is already included? See https://github.com/gurusabarish/hugo-profile/pull/83
